#!/bin/sh
### BEGIN INIT INFO
# Provides:          urtbod-server
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: URTBOD Tunnel Server
### END INIT INFO

# URTBOD server using SSH over SSL - Requires private key and cert for 
# server plus CA certificate used for client certificates.

# Run a socat listener on $LISTENPORT that forwards SSH over SSL
LISTENPORT=443

# A PEM file containing the private key and cert for this server
SERVERCERT=/etc/ssl/private/`hostname`.pem

# A PEM file containing the certificate used to sign client certs
# (or the client cert itself if it is self-signed)
CACERT=/etc/ssl/certs/remotes.crt

case "$1" in
  start)
        # Fire!
        echo "Starting URTBOD server on port ${LISTENPORT}"
        /usr/bin/socat ssl-l:${LISTENPORT},reuseaddr,fork,cert=${SERVERCERT},cafile=${CACERT} exec:'/usr/sbin/sshd -i' &
        exit 0
  ;;

  stop)
        pkill socat
  ;;
esac

exit 0

